INSERT INTO STUDENTS (LAST_NAME, FIRST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('JUAN', 'DER', '2002-01-02', 'TRUE');
INSERT INTO STUDENTS (LAST_NAME, FIRST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Miguel', 'ar', '2000-01-03', 'TRUE');
INSERT INTO STUDENTS (LAST_NAME, FIRST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Adria', 'rtyu', '2000-05-02', 'FALSE');
INSERT INTO STUDENTS (LAST_NAME, FIRST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Jose', 'bgou', '2003-01-02', 'TRUE');
INSERT INTO STUDENTS (LAST_NAME, FIRST_NAME, BIRTH_DATE, WANTS_NEWS_LETTER) VALUES ('Aaron', 'vbuuyy', '2001-02-02', 'FALSE');

INSERT INTO COURSE (TITLE) VALUES ('M1');
INSERT INTO COURSE (TITLE) VALUES ('M2');
INSERT INTO COURSE (TITLE) VALUES ('M3');
INSERT INTO COURSE (TITLE) VALUES ('M4');
INSERT INTO COURSE (TITLE) VALUES ('M5');
INSERT INTO COURSE (TITLE) VALUES ('M6');
INSERT INTO COURSE (TITLE) VALUES ('M7');
INSERT INTO COURSE (TITLE) VALUES ('M8');

INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('javascript.com', '3');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('java.com', '4');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('php.com', '5');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('openwebinars.com', '1');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('yava.com', '1');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('w3schools.com', '1');
INSERT INTO COURSE_MATERIAL (URL, COURSE_ID) VALUES ('sfgwuhyhcyv.com', '3');

INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('1', '3');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('1', '5');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('1', '6');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('2', '1');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('2', '2');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('2', '4');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('3', '1');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('3', '2');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('4', '2');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('4', '3');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('4', '4');
INSERT INTO COURSE_STUDENTS (ID, COURSE_ID) VALUES ('4', '5');



